### ISSUE TITLE
training slow

### ISSUE THREAD

**Issue by jiangix-paper** [databricks/dbrx#6]
Hello, I find it is slow to train the moe model, because the DbrxExperts moe training process is serial.
<img width="616" alt="image" src="https://github.com/databricks/dbrx/assets/62198809/e2ead177-f5c3-433e-a1b8-c04432defe79">

Can it use parallel training process in "for loop"？

**Comment by hanlint** [comment]
Hi @jiangix-paper , correct this is an unoptimized reference implementation. Parallelization is possible with MegaBlocks, we will be pushing more updates over time!
